apiVersion: v1
kind: Service
metadata:
  name: city-api-service
spec:
  ports:
  - port: 80
  selector:
    matchLabels:
      app: quarkus-city-api
      version: 1.0.0
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  ports:
    - port: 5032
      targetPort: 5032
  selector:
    matchLabels:
      app: quarkus-database
      version: 1.0.0
  type: ClusterIPw