#Make a job that build and push each image on ghcr.io
name: Docker build and push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout the code
      uses: actions/checkout@v2
      with:
        ref: fruits
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - 
      name: Compile the package Quarkus
      run : |
        mvn -N io.takari:maven:wrapper
        ./mvnw package -DskipTests
    -
      name: Build and push the Dockerfile
      uses: docker/build-push-action@v3
      with:
        file: ./src/main/docker/Dockerfile.jvm
        tags: gridexx/city-api:latest