#Make a job that test
name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout the code
      uses: actions/checkout@v2
    - 
      name: Compile the package Quarkus
      run : mvn -N io.takari:maven:wrapper
    - 
      name: run tests
      run : mvn test
    